In [3]:
import MultiTaskBattery.battery as bat
import Functional_Fusion.atlas_map as am
import numpy as np

In [4]:
base_dir='Y:/data/FunctionalFusion_new'

# Cortical batteries

In [5]:
atlas = 'fs32k'
atlas_obj,_= am.get_atlas(atlas)
data_cortex,info = bat.fetch_task_library(atlas= atlas,version='V1')
full_code = info['task_code'] + '_' + info['cond_code']

Downloading data from 'https://api.github.com/repos/Barafat2/MTB_task_library/contents/V1/desc-tasksV1_space-fs32k_beta.dscalar.nii' to file 'C:\Users\barafat\AppData\Local\MTB_task_library\MTB_task_library\Cache\V1\desc-tasksV1_space-fs32k_beta.dscalar.nii'.

SHA256 hash of downloaded file: 94a610e317b459be73ec769aaadb177f2722d5364fa1a7e1b2af68d815639858
Use this value as the 'known_hash' argument of 'pooch.retrieve' to ensure that the file hasn't changed if it is downloaded again in the future.
Downloading data from 'https://api.github.com/repos/Barafat2/MTB_task_library/contents/V1/desc-tasksV1_info.tsv' to file 'C:\Users\barafat\AppData\Local\MTB_task_library\MTB_task_library\Cache\V1\desc-tasksV1_info.tsv'.
SHA256 hash of downloaded file: 9595d553e195f1edcb61b55098de09c09f7a89aea4c9090a6a8b71f7ff7263e1
Use this value as the 'known_hash' argument of 'pooch.retrieve' to ensure that the file hasn't changed if it is downloaded again in the future.

Loaded 78 conditions, 59518 vertices

Motor and PFC ROIS

In [6]:
atlas_dir = f'{base_dir}/Atlases/tpl-fs32k'
model_name_L = f'{atlas_dir}/glasser.L.label.gii'
model_name_R = f'{atlas_dir}/glasser.R.label.gii'
parcels = atlas_obj.read_data([model_name_L,model_name_R])

ROI_motor = np.isin(parcels, [53,9,8,39,36,37,96,54,44,55,78,56,42]).astype(int)[np.newaxis, :]
ROI_PFC = np.isin(parcels, [74,81,82,83,84,86]).astype(int)[np.newaxis, :]

Motor and PFC batteries

In [7]:
data_motor = data_cortex * ROI_motor
motor_df= bat.get_top_batteries(data_motor,full_code,n_samples=1000000, battery_size=8, n_top_batteries=10,forced_tasks=None)
display(motor_df)

Starting computation... (forced: 0, random: 8)
Processed 100,000 / 1,000,000 (10.0%) | Batch: 6.70s | Rate: 11638/s | ETA: 77s
Processed 200,000 / 1,000,000 (20.0%) | Batch: 0.71s | Rate: 17835/s | ETA: 45s
Processed 300,000 / 1,000,000 (30.0%) | Batch: 0.70s | Rate: 21698/s | ETA: 32s
Processed 400,000 / 1,000,000 (40.0%) | Batch: 0.70s | Rate: 24316/s | ETA: 25s
Processed 500,000 / 1,000,000 (50.0%) | Batch: 0.69s | Rate: 26230/s | ETA: 19s
Processed 600,000 / 1,000,000 (60.0%) | Batch: 0.68s | Rate: 27683/s | ETA: 14s
Processed 700,000 / 1,000,000 (70.0%) | Batch: 0.71s | Rate: 28834/s | ETA: 10s
Processed 800,000 / 1,000,000 (80.0%) | Batch: 0.69s | Rate: 29774/s | ETA: 7s
Processed 900,000 / 1,000,000 (90.0%) | Batch: 0.68s | Rate: 30552/s | ETA: 3s
Processed 1,000,000 / 1,000,000 (100.0%) | Batch: 0.70s | Rate: 31181/s | ETA: 0s

Total time: 32.1s (31181 samples/s)

   rank           nit                                              tasks
0     1 -1.000000e+12  [actobserv_action, nbckverb_2bcknrep, sptialma...
1     2 -1.000000e+12  [actobserv_action, fingr_sequence, vrbgen_gene...
2     3 -1.000000e+12  [intrval_task, fingr_sequence, vrbgen_generate...
3     4 -1.000000e+12  [gng_go, actobserv_action, fingr_sequence, vrb...
4     5 -1.000000e+12  [actobserv_action, affect_pleasant, vrbgen_gen...
5     6 -1.000000e+12  [gng_go, actobserv_action, fingr_simple, movie...
6     7 -1.000000e+12  [actobserv_action, mtrimgry_task, fingr_sequen...
7     8 -1.000000e+12  [actobserv_action, movie_nature, mntalrot_diff...
8     9 -1.000000e+12  [fingr_simple, nbckverb_2bckrep, movie_nature,...
9    10 -1.000000e+12  [emotface_sad, mtrimgry_task, fingr_sequence, ...

In [8]:
motor_df['tasks'][0]

['actobserv_action',
 'nbckverb_2bcknrep',
 'sptialmap_med',
 'biomotion_normal',
 'motor_tongue',
 'dmndgrid_g12s3b2',
 'motor_lfoot',
 'motor_lhand']

In [10]:
data_pfc = data_cortex * ROI_PFC
pfc_df= bat.get_top_batteries(data_pfc,full_code,n_samples=1000000, battery_size=8, n_top_batteries=10,forced_tasks=None)
display(pfc_df)

Starting computation... (forced: 0, random: 8)
Processed 100,000 / 1,000,000 (10.0%) | Batch: 0.69s | Rate: 39525/s | ETA: 23s
Processed 200,000 / 1,000,000 (20.0%) | Batch: 0.70s | Rate: 39102/s | ETA: 20s
Processed 300,000 / 1,000,000 (30.0%) | Batch: 0.71s | Rate: 38892/s | ETA: 18s
Processed 400,000 / 1,000,000 (40.0%) | Batch: 0.72s | Rate: 38703/s | ETA: 16s
Processed 500,000 / 1,000,000 (50.0%) | Batch: 0.69s | Rate: 38717/s | ETA: 13s
Processed 600,000 / 1,000,000 (60.0%) | Batch: 0.69s | Rate: 38758/s | ETA: 10s
Processed 700,000 / 1,000,000 (70.0%) | Batch: 0.69s | Rate: 38751/s | ETA: 8s
Processed 800,000 / 1,000,000 (80.0%) | Batch: 0.69s | Rate: 38704/s | ETA: 5s
Processed 900,000 / 1,000,000 (90.0%) | Batch: 0.68s | Rate: 38720/s | ETA: 3s
Processed 1,000,000 / 1,000,000 (100.0%) | Batch: 0.69s | Rate: 38731/s | ETA: 0s

Total time: 25.8s (38729 samples/s)

   rank           nit                                              tasks
0     1 -1.000000e+12  [gng_ngo, arith_math, mtrimgry_task, vrbgen_ge...
1     2 -1.000000e+12  [tom_task, arith_math, mtrimgry_task, nbckpic_...
2     3 -1.000000e+12  [affect_pleasant, mtrimgry_task, vrbgen_genera...
3     4 -1.000000e+12  [gng_ngo, tom_task, affect_unpleasant, nbckver...
4     5 -1.000000e+12  [gng_ngo, nbckpic_2bckrep, vrbgen_generate, mo...
5     6 -1.000000e+12  [tom_task, arith_math, emotface_happy, mtrimgr...
6     7 -1.000000e+12  [gng_ngo, arith_math, nbckverb_2bckrep, vrbgen...
7     8 -1.000000e+12  [gng_ngo, affect_pleasant, vrbgen_generate, sp...
8     9 -1.000000e+12  [gng_ngo, tom_task, arith_digitjudgement, mtri...
9    10 -1.000000e+12  [affect_unpleasant, vrbgen_generate, sntncpred...

# Cerebellum

In [24]:
atlas = 'SUIT3'
atlas_obj,_= am.get_atlas(atlas)
data_cerebellum,info = bat.fetch_task_library(atlas= atlas,version='V1')
full_code = info['task_code'] + '_' + info['cond_code']

Loaded 79 conditions, 6918 vertices

In [25]:
cb_df= bat.get_top_batteries(data_cerebellum,full_code,n_samples=1000000, battery_size=8, n_top_batteries=10,forced_tasks=None)
display(pfc_df)

Starting computation... (forced: 0, random: 8)
Processed 100,000 / 1,000,000 (10.0%) | Batch: 0.72s | Rate: 38986/s | ETA: 23s
Processed 200,000 / 1,000,000 (20.0%) | Batch: 0.75s | Rate: 38322/s | ETA: 21s
Processed 300,000 / 1,000,000 (30.0%) | Batch: 0.72s | Rate: 38183/s | ETA: 18s
Processed 400,000 / 1,000,000 (40.0%) | Batch: 0.72s | Rate: 38469/s | ETA: 16s
Processed 500,000 / 1,000,000 (50.0%) | Batch: 0.73s | Rate: 38646/s | ETA: 13s
Processed 600,000 / 1,000,000 (60.0%) | Batch: 0.71s | Rate: 38685/s | ETA: 10s
Processed 700,000 / 1,000,000 (70.0%) | Batch: 0.73s | Rate: 38721/s | ETA: 8s
Processed 800,000 / 1,000,000 (80.0%) | Batch: 0.72s | Rate: 38850/s | ETA: 5s
Processed 900,000 / 1,000,000 (90.0%) | Batch: 0.71s | Rate: 38899/s | ETA: 3s
Processed 1,000,000 / 1,000,000 (100.0%) | Batch: 0.71s | Rate: 38936/s | ETA: 0s

Total time: 25.7s (38936 samples/s)

   rank           nit                                              tasks
0     1 -1.000000e+12  [tom_task, emotface_happy, vrbgen_generate, hc...
1     2 -1.000000e+12  [nbckverb_2bcknrep, vrbgen_generate, biomotion...
2     3 -1.000000e+12  [affect_pleasant, vrbgen_generate, sptialmap_m...
3     4 -1.000000e+12  [nbckpic_2bcknrep, vrbgen_generate, hcplanguag...
4     5 -1.000000e+12  [vrbgen_generate, biomotion_scrambeled, hcplan...
5     6 -1.000000e+12  [stroop_incon, vrbgen_generate, sptialmap_diff...
6     7 -1.000000e+12  [stroop_incon, vrbgen_generate, sptialmap_diff...
7     8 -1.000000e+12  [stroop_con, vrbgen_generate, biomotion_normal...
8     9 -1.000000e+12  [gng_ngo, nbckverb_2bckrep, vrbgen_generate, m...
9    10 -1.000000e+12  [tom_task, affect_pleasant, vrbgen_generate, b...